apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: service-mesh-entry
spec:
  hosts:
  - service-mesh
  ports:
  - number: 80
    name: http
    protocol: HTTP
  location: MESH_INTERNAL
  resolution: NONE
